name: Deploy Vue3 App

on:
  push:
    branches:
      - master  # Change this to your default branch if it's different (e.g., 'master')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Change to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages (or another platform)
        run: |
          # Example for deploying to GitHub Pages
          npm install -g gh-pages
          gh-pages -d dist  # Adjust if your build output is in a different folder
