name: Deploy Vue3 App to GitHub Pages

on:
  push:
    branches:
      - master  # Runs the workflow when pushing to 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Make sure your build output goes to 'dist/'

      - name: Configure Git user
        run: |
          git config --global user.name "Rubel Ahmed"
          git config --global user.email "nus01ta3@gmail.com"

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.SAFE_HAJJ }}@github.com/${{ github.repository }}.git
          npx gh-pages -d dist
        env:
          GITHUB_TOKEN: ${{ secrets.SAFE_HAJJ }}
